openapi: 3.0.0
info:
  title: Voting API
  version: 1.0.0
  description: An API for creating and participating in polls.

paths:
  /polls:
    get:
      summary: Retrieve a list of all polls
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                polls:
                  - id: 1
                    question: 'Favorite Programming Language?'
                    options:
                      - option_id: 1
                        text: 'Python'
                        votes: 10
                      - option_id: 2
                        text: 'JavaScript'
                        votes: 15

    post:
      summary: Create a new poll
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      text:
                        type: string
              required:
                - question
                - options
      responses:
        '201':
          description: Poll created successfully
          content:
            application/json:
              example:
                id: 2
                message: Poll created

  /polls/{pollId}:
    get:
      summary: Retrieve a specific poll by ID
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                question: 'Favorite Programming Language?'
                options:
                  - option_id: 1
                    text: 'Python'
                    votes: 10
                  - option_id: 2
                    text: 'JavaScript'
                    votes: 15

    post:
      summary: Vote in a specific poll
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                option_id:
                  type: integer
              required:
                - option_id
      responses:
        '201':
          description: Vote recorded successfully
          content:
            application/json:
              example:
                id: 1
                message: Vote recorded
